# Generated by Django 3.1.4 on 2020-12-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=3024, null=True)),
                ('author', models.CharField(max_length=120)),
            ],
        ),
    ]
